version: '3'
services:
  proxy:
    build: .
    networks:
      - applications
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/nginx/conf.d
networks:
  applications:
    name: applications
    external: true